version: '3.1'
services:
  app:
    container_name: springboot-app
    image: spring-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=lostrelos
      - POSTGRES_USER=postgres
      - POSTGRES_DB=voda
      - DB_ADDR_ALIAS=db
    volumes:
      - ./postgres-data:/var/lib/postgresqldb/data
volumes:
  postgres-data:

